# Generated by Django 4.1 on 2022-08-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_publishedpost_imagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='access_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
