# Generated by Django 4.1 on 2022-08-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_schedule_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpost',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
